= Paralela Anthony Sanchez Quiros

== Pthreads

[%autowidth]
|===
|# |Id |Type |Description
|1 |link:pthreads/commented_examples[commented_examples] |Homework | Basic
example of pthread_create.
|2 |link:pthreads/recursive_hello[recursive_hello] |Homework | Recursive
creating of threads.
|3 |link:pthreads/invert[invert] |Class_example |Serial program that invert
integer numbers gived in the standar entrance
|4 |link:pthreads/recursive_hello/trace[recursive_hello_trace] |Homework |
Memory trace of recursive_hello
|5 |link:pthreads/hello_w[hello_w] |Homework | Creating and joining threads
with cycle for
|6 |link:pthreads/grandma_lottery[grandma_lottery] |Class_example |Serial
program that invert integer numbers gived in the standar entrance
|7 |link:pthreads/hello_iwi_pri[hello_iwi_pri] |Homework | Basic example of
thread private data
|8 |link:pthreads/hello_iwi_shr[hello_iwi_shr] |Homework | Basic example of
thread public data
|9 |link:pthreads/hello_order_busywait[hello_order_busywait] |Homework | Basic
example of thread busy waiting
|10 |link:pthreads/team_shot_put[team_shot_put] |Homework | The program takes as
input n teams, each consisting of m athletes. Each athlete performs multiple
throws, and their best attempt is recorded. The program uses threads to handle
the execution efficiently. After all throws are processed, the team with the
highest combined best throws is declared the winner.
|11 |link:pthreads/create_thread_team[create_thread_team] |Class_example |
Exercise to solve team_shot_put using pthreads teams instead of normal pthreads
|12 |link:pthreads/race_position[race_position] |Homework | This program
simulates a race condition among threads, where only one thread can reach
position x, but the outcome is non-deterministic.
|13 |link:pthreads/hello_order_semaphor[hello_order_semaphor] |Homework | 
This program allow only one thread to print a greeting at the same time using
a semaphore for the threads
|14 |link:pthreads/birthday_pinata[birthday_pinata] |Class_example | This
program simulates a birthday party scenario where all threads must hit the
pinata until it breaks. The thread that breaks the piñata must announce it.
|15 |link:pthreads/hello_order_cond_safe[hello_order_cond_safe] |Homework |
A program that allows threads to print in order using conditional safe to avoid
busy-waiting
|===

== Tasks

== Glosary

=== Programacion serial

Es un paradigma de programacion donde la realizacion de tareas es serial, es decir, se realiza primeramente tarea1 y hasta que no sea
finalizada, no se prosigue con tarea2


=== Programacion Concurrente

Es un paradigma de programacion que puede basarse en la programacion iperativa o funcional. A diferencia de la programacion serial, la concurrente puede realizar varias tareas a la vez. Un ejemplo seria, mientras tarea01 termina, ir realizando tarea2


=== Programacion paralela

Se refiere a la programacion que es capaz de realizar varias tareas al mismo tiempo. Es decir, realizar tarea1 y tarea2 a la vez, en el mismo instante


=== Concurrencia de tareas

Se refiere a cuando varios hilos acceden a los mismos datos, esto puede generar problemas de condiciones de carreras.


=== Paralelismo de datos

Se refiere a cuando un conjunto de datos es trabajado es dividido en fragmentos y cada fragmento es procesado en paralelo en distintas unidades de procesamiento


=== Hilo de ejecucion

Un hilo de ejecucion se refiere a un ejecutante capaz de realizar tareas de forma paralela con otros ejecutantes (hilos).
=== Indeterminismo

El indeterminismo es cuando no se sabe que hilo terminara su trabajo primero, poniendo un ejemplo seria enviar 2 hilos a realizar exactamente la misma tarea. A veces el hilo 1 terminara primero, a veces sera el segundo.


=== Memoria privada y compartida
=== Espera activa
=== Condicion de carrera
=== Control de concurrencia
=== Seguridad condicional
=== Exclusion mutua
=== Semaforo
=== Barrera
=== Variable de condicion
=== Candado de lectura y escritura
=== Descomposicion
=== Mapeo
=== Incremento de velocidad
=== Eficiencia
=== Comunicacion punto a punto entre procesos
=== Comunicacion colectiva entre procesos
=== Reduccion