= Tarea01 serial
:toc-title: Tabla de contenidos
:experimental:
:nofooter:
:source-highlighter: pygments
:sectnums:
:stem: latexmath
:toc:
:xrefstyle: short

[[descripcion del problema]]

== Descripcion del problema

Se debe crear una simulación que ayude a encontrar el momento de equilibrio térmico de una lámina RxC (R número de columnas y C número de filas), la cual recibe calor constante por el borde.

Estas láminas serán matrices donde cada celda almacena una temperatura, la cual cambia según el estado k y la temperatura de las celdas cercanas (arriba, abajo, izquierda, derecha). La temperatura actual será la suma de las 4 celdas adyacentes.
La formula utilizada para actualizar las celdas es:
[stem]
++++
T_{i,j}^{k+1} = T_{i,j}^k + \frac{\Delta t \cdot \alpha}{h^2} (T_{i-1,j}^k + T_{i,j+1}^k + T_{i+1,j}^k + T_{i,j-1}^k - 4T_{i,j}^k)
++++

Además, cada celda puede perder temperatura, distribuyéndola en las 4 celdas adyacentes. La transferencia depende del área que recorre (tamaño de la celda). A medida que pasa el tiempo, más calor se transfiere a las celdas adyacentes. La cantidad de energía intercambiada dependerá de la calidad conductora de la lámina.

El programa finaliza cuando se alcanza el punto de equilibrio térmico. Este se calcula a partir de un parámetro epsilon, que representará el mínimo cambio de temperatura significativo. Si una sola de las celdas tiene un cambio de temperatura mayor a epsilon, la simulación debe continuar.

La diferencia a comparar con epsilon de cada celda será la resta del valor en el estado k y el valor en el estado k+1, donde:

* Estado k: estado de la lámina transcurridos 0 minutos.
* Estado k+1: estado de la lámina transcurridos 20 minutos.

#Si el valor más grande de toda la lámina es menor a epsilon, el programa finalizará.#

[[manual]]

== Manual del usuario

1. Instalar dependencias:
- Asegúrate de tener instalados todos los paquetes necesarios:

[source, bash]
---
 make instdeps
---

=== Guía de Uso

1. Compilar el Proyecto:
- Navega a la carpeta `serial` y compila con `make`
De esta manera se creara el ejecutable en la carpeta bin.
Una vez compilado el proyecto, puedes ejecutarlo usando el siguiente comando:

[source, bash]
----
./bin/serial ./jobs/job###/job###.txt
----

Donde ### es el número del job a utilizar en el programa. Ejemplo:
[source, bash]
----
./jobs/job001b/job002.txt
----

== Ejemplo de entrada y salida

=== Input
Cada archivo txt cuenta con varias placas para ser procesadas, en este readme se agrega solo dos de dichas placas.

[source, bash]
---
./bin/serial ./jobs/job002b/job002.txt
---

Laminas leidas:

[source, bash]
plate001.bin	1	50	1000	1e-14	129570	0000/00/01	11:59:30
plate002.bin	1	25	1000	1e-14	250939	0000/00/02	21:42:19

=== Salida
La salida es escrita en un archivo tsv cuyo contenido para la primera lamina es:
[source, bash]
plate001.bin	1	50	1000	1e-14	0000/00/01	11:59:30

Contenido del archivo tsv de la segunda lamina:
[source,bash]
plate002.bin	1	25	1000	1e-14	0000/00/02	21:42:19

[[creditos]]
== Creditos

Creditos a Jeisson Hidalgo-Céspedes, pues fue quien brindo el make y la guia de como realizar este proyecto.

https://jeisson.ecci.ucr.ac.cr/concurrente/2025a/tareas/#pthread[Link al enunciado original de la tarea]

Creditos a Anthony Sanchez Quiros por la realizacion de todo el codigo de este programa.