= Tarea01 serial
:experimental:
:nofooter:
:source-highlighter: pygments
:sectnums:
:stem: latexmath
:toc:
:xrefstyle: short

[[problem_description]]
== Problem Description

Se debe crear una simulación que ayude a encontrar el momento de equilibrio térmico de una lámina RxC (R número de columnas y C número de filas), la cual recibe calor constante por el borde.

Estas láminas serán matrices donde cada celda almacena una temperatura, la cual cambia según el estado k y la temperatura de las celdas cercanas (arriba, abajo, izquierda, derecha). La temperatura actual será la suma de las 4 celdas adyacentes.
La formula utilizada para actualizar las celdas es:
[stem]
++++
T_{i,j}^{k+1} = T_{i,j}^k + \frac{\Delta t \cdot \alpha}{h^2} (T_{i-1,j}^k + T_{i,j+1}^k + T_{i+1,j}^k + T_{i,j-1}^k - 4T_{i,j}^k)
++++

Además, cada celda puede perder temperatura, distribuyéndola en las 4 celdas adyacentes. La transferencia depende del área que recorre (tamaño de la celda). A medida que pasa el tiempo, más calor se transfiere a las celdas adyacentes. La cantidad de energía intercambiada dependerá de la calidad conductora de la lámina.

El programa finaliza cuando se alcanza el punto de equilibrio térmico. Este se calcula a partir de un parámetro epsilon, que representará el mínimo cambio de temperatura significativo. Si una sola de las celdas tiene un cambio de temperatura mayor a epsilon, la simulación debe continuar.

La diferencia a comparar con epsilon de cada celda será la resta del valor en el estado k y el valor en el estado k+1, donde:

* Estado k: estado de la lámina transcurridos 0 minutos.
* Estado k+1: estado de la lámina transcurridos 20 minutos.

#Si el valor más grande de toda la lámina es menor a epsilon, el programa finalizará.#

[[user_manual]]
== User Manual

=== Build

1. Instalar dependencias:
- Asegúrate de tener instalados todos los paquetes necesarios:


=== Guía de Uso

1. Compilar el Proyecto:
- Navega a la carpeta `serial` y compila con `make`
De esta manera se creara el ejecutable en la carpeta bin.
Una vez compilado el proyecto, puedes ejecutarlo usando el siguiente comando:
[source, bash]
----
./bin/serial ./jobs/job###/job###.txt
----

Donde ### es el número del job a utilizar en el programa. Ejemplo:
[source, bash]
----
./jobs/job001b/job002.txt
----

[[credits]]
== Credits

Creditos a Jeisson Hidalgo-Céspedes, pues fue quien brindo el make y la guia de como realizar este proyecto.

https://jeisson.ecci.ucr.ac.cr/concurrente/2025a/tareas/#pthread[Link al enunciado original de la tarea]

Creditos a Anthony Sanchez Quiros por la realizacion de todo el codigo de este programa.